/**
 * Utility to convert Markdown or plain text into a well-formed LaTeX (.tex) document.
 * Prevents "! LaTeX Error: Undefined color `black!30'" and provides full support for
 * colored text, tables, figures, code listings, and typography.
 */
export function convertToLaTeX(filename: string, content: string, format: string): string {
  const baseName = filename.substring(0, filename.lastIndexOf('.')) || filename;
  
  // If it's already a raw LaTeX file, ensure xcolor & color definitions exist if needed
  if (format === 'tex') {
    if (content.includes('\\documentclass') && !content.includes('\\usepackage[table]{xcolor}') && !content.includes('\\usepackage[table,dvipsnames,svgnames]{xcolor}')) {
      // If xcolor is missing or loaded without table/color mixing, inject the safe preamble definitions
      if (!content.includes('{xcolor}')) {
        return content.replace(
          /\\documentclass(\[[^\]]*\])?\{[^}]+\}/,
          `$&\n\\usepackage[table,dvipsnames,svgnames]{xcolor}\n\\usepackage{colortbl}\n\\providecolor{black}{rgb}{0,0,0}\n\\colorlet{black!30}{black!30}`
        );
      }
    }
    return content;
  }

  // Create robust preamble with color mixing, table, and hyperref safety
  let tex = `% LaTeX Document generated by LiViA (Light Vi Again)
\\documentclass[11pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage[italian,english]{babel}
\\usepackage{geometry}
\\geometry{a4paper, margin=1in}
\\usepackage{amsmath,amssymb}

% Load xcolor with table, dvipsnames and svgnames BEFORE listings and hyperref
\\usepackage[table,dvipsnames,svgnames]{xcolor}
\\usepackage{colortbl}
\\usepackage{listings}
\\usepackage{booktabs}
\\usepackage{hyperref}

% Guarantee black, white, gray base colors and color-mixing tints (prevents Undefined color 'black!30')
\\providecolor{black}{rgb}{0,0,0}
\\providecolor{white}{rgb}{1,1,1}
\\providecolor{gray}{rgb}{0.5,0.5,0.5}
\\providecolor{lightgray}{rgb}{0.83,0.83,0.83}
\\providecolor{darkgray}{rgb}{0.25,0.25,0.25}

% Fallback definition for black!30 and common tints so compiling never fails
\\colorlet{black!30}{black!30}
\\colorlet{black!10}{black!10}
\\colorlet{black!20}{black!20}
\\colorlet{black!50}{black!50}
\\colorlet{gray!10}{gray!10}
\\colorlet{gray!20}{gray!20}
\\colorlet{gray!30}{gray!30}

% Configuration for listings / code display
\\definecolor{codegray}{rgb}{0.5,0.5,0.5}
\\definecolor{codeblue}{rgb}{0.13,0.38,0.56}
\\definecolor{codegreen}{rgb}{0.1,0.5,0.1}
\\definecolor{codeframe}{rgb}{0.8,0.8,0.8}
\\definecolor{codebg}{rgb}{0.98,0.98,0.98}
\\lstset{
  basicstyle=\\ttfamily\\small,
  breaklines=true,
  captionpos=b,
  commentstyle=\\color{codegreen},
  keywordstyle=\\color{codeblue},
  numberstyle=\\tiny\\color{codegray},
  numbers=left,
  stepnumber=1,
  numbersep=8pt,
  showstringspaces=false,
  frame=single,
  rulecolor=\\color{codeframe},
  backgroundcolor=\\color{codebg}
}

\\title{${baseName.replace(/_/g, '\\_')}}
\\author{LiViA Document Editor}
\\date{\\today}

\\begin{document}

\\maketitle

`;

  if (format !== 'md' && format !== 'txt') {
    // For source code formats, wrap in a listings environment
    const langMap: Record<string, string> = {
      py: 'Python',
      js: 'JavaScript',
      ts: 'TypeScript',
      kt: 'Kotlin',
      bash: 'bash',
      sh: 'bash',
      json: 'JSON',
      xml: 'XML',
      c: 'C',
      cpp: 'C++',
      java: 'Java',
      rs: 'Rust',
      go: 'Go',
      sql: 'SQL',
      html: 'HTML',
      css: 'CSS'
    };
    const detectedLang = langMap[format] || '';
    const lstOptions = detectedLang ? `[language=${detectedLang}]` : '';
    
    tex += `\\begin{lstlisting}${lstOptions}\n${content}\n\\end{lstlisting}\n`;
  } else {
    // Parse Markdown to LaTeX
    const lines = content.split('\n');
    let inList = false;
    let listType: 'itemize' | 'enumerate' | null = null;
    let inCodeBlock = false;
    let inTable = false;
    let tableRows: string[][] = [];

    const flushTable = () => {
      if (!inTable || tableRows.length === 0) return;
      const numCols = Math.max(...tableRows.map(r => r.length));
      const colSpec = Array(numCols).fill('l').join(' | ');
      
      tex += `\\begin{center}\n\\begin{tabular}{| ${colSpec} |}\n\\hline\n`;
      tableRows.forEach((row, rIdx) => {
        const paddedRow = [...row];
        while (paddedRow.length < numCols) paddedRow.push('');
        const formattedCells = paddedRow.map(c => formatMarkdownInline(c.trim()));
        tex += `  ${formattedCells.join(' & ')} \\\\\n\\hline\n`;
        if (rIdx === 0 && tableRows.length > 1) {
          tex += `\\hline\n`; // Double line under header
        }
      });
      tex += `\\end{tabular}\n\\end{center}\n\\vspace{0.5em}\n`;
      
      inTable = false;
      tableRows = [];
    };

    for (let i = 0; i < lines.length; i++) {
      let line = lines[i];

      // Handle Code Blocks
      if (line.trim().startsWith('```')) {
        flushTable();
        if (inCodeBlock) {
          tex += `\\end{lstlisting}\n\n`;
          inCodeBlock = false;
        } else {
          if (inList) {
            tex += `\\end{${listType}}\n\n`;
            inList = false;
            listType = null;
          }
          const lang = line.replace('```', '').trim();
          const lstOptions = lang ? `[language=${lang}]` : '';
          tex += `\\begin{lstlisting}${lstOptions}\n`;
          inCodeBlock = true;
        }
        continue;
      }

      if (inCodeBlock) {
        tex += line + '\n';
        continue;
      }

      // Handle Markdown Tables (| col1 | col2 |)
      const trimmedLine = line.trim();
      if (trimmedLine.startsWith('|') && trimmedLine.endsWith('|') && trimmedLine.length > 2) {
        if (inList) {
          tex += `\\end{${listType}}\n\n`;
          inList = false;
          listType = null;
        }
        // Check if it's a separator line (| --- | :---: | ---: |)
        const isSep = trimmedLine.split('|').slice(1, -1).every(cell => /^[\s:-]+$/.test(cell.trim()));
        if (!isSep) {
          const cells = trimmedLine.split('|').slice(1, -1);
          tableRows.push(cells);
          inTable = true;
        }
        continue;
      } else if (inTable) {
        flushTable();
      }

      // Handle horizontal rules
      if (line.trim() === '---' || line.trim() === '***') {
        if (inList) {
          tex += `\\end{${listType}}\n\n`;
          inList = false;
          listType = null;
        }
        tex += `\\hrule\n\\vspace{0.5em}\n`;
        continue;
      }

      // Handle Headers
      if (line.startsWith('#')) {
        if (inList) {
          tex += `\\end{${listType}}\n\n`;
          inList = false;
          listType = null;
        }
        const depth = line.match(/^#+/)?.[0].length || 1;
        const headerText = line.replace(/^#+\s*/, '').trim();
        const escapedHeader = formatMarkdownInline(headerText);
        
        if (depth === 1) {
          tex += `\\section{${escapedHeader}}\n`;
        } else if (depth === 2) {
          tex += `\\subsection{${escapedHeader}}\n`;
        } else {
          tex += `\\subsubsection{${escapedHeader}}\n`;
        }
        continue;
      }

      // Handle Lists (Unordered)
      const unorderedMatch = line.match(/^(\s*)([-*+])\s+(.*)$/);
      if (unorderedMatch) {
        const itemText = unorderedMatch[3];
        const formattedItem = formatMarkdownInline(itemText);
        if (!inList || listType !== 'itemize') {
          if (inList) {
            tex += `\\end{${listType}}\n\n`;
          }
          tex += `\\begin{itemize}\n`;
          inList = true;
          listType = 'itemize';
        }
        tex += `  \\item ${formattedItem}\n`;
        continue;
      }

      // Handle Lists (Ordered)
      const orderedMatch = line.match(/^(\s*)(\d+)\.\s+(.*)$/);
      if (orderedMatch) {
        const itemText = orderedMatch[3];
        const formattedItem = formatMarkdownInline(itemText);
        if (!inList || listType !== 'enumerate') {
          if (inList) {
            tex += `\\end{${listType}}\n\n`;
          }
          tex += `\\begin{enumerate}\n`;
          inList = true;
          listType = 'enumerate';
        }
        tex += `  \\item ${formattedItem}\n`;
        continue;
      }

      // If we were in a list but current line is not a list item and is not empty, close the list
      if (inList && line.trim() !== '') {
        const nextLine = lines[i + 1] || '';
        const isNextList = nextLine.match(/^(\s*)([-*+])\s+(.*)$/) || nextLine.match(/^(\s*)(\d+)\.\s+(.*)$/);
        if (!isNextList) {
          tex += `\\end{${listType}}\n\n`;
          inList = false;
          listType = null;
        }
      }

      // Process normal paragraph line
      if (line.trim() !== '') {
        const formattedLine = formatMarkdownInline(line);
        tex += formattedLine + '\n';
      } else {
        tex += '\n'; // Keep paragraph separations
      }
    }

    // Flush any open table
    if (inTable) {
      flushTable();
    }

    // Close any unclosed list
    if (inList) {
      tex += `\\end{${listType}}\n\n`;
    }
  }

  tex += `\n\\end{document}\n`;
  return tex;
}

// Escapes LaTeX special characters
function escapeLaTeXSpecial(text: string): string {
  return text
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([&%$#_{}])/g, '\\$1')
    .replace(/\^/g, '\\textasciicircum{}')
    .replace(/~/g, '\\textasciitilde{}');
}

// Format markdown inline formatting like bold, italic, color tags, inline code, and links
function formatMarkdownInline(text: string): string {
  let res = text;
  
  // Replace custom color tags <color:#HEX>text</color> or <color:name>text</color>
  res = res.replace(/<color:(#?[a-zA-Z0-9_!]+)>(.*?)<\/color>/gi, (_match, colorVal: string, innerTxt: string) => {
    if (colorVal.startsWith('#')) {
      const hex = colorVal.substring(1);
      return `QQQCOLORHEXST${hex}QQQMID${innerTxt}QQQCOLOREN`;
    } else {
      return `QQQCOLORNAMEST${colorVal}QQQMID${innerTxt}QQQCOLOREN`;
    }
  });

  // Replace links with placeholders
  res = res.replace(/\[(.*?)\]\((.*?)\)/g, 'QQQLINKST$1QQQLINKMID$2QQQLINKEN');
  
  // Substitute markdown inline tags with safe alphanumeric placeholders
  res = res.replace(/\*\*(.*?)\*\*/g, 'QQQBOLDST$1QQQBOLDEN');
  res = res.replace(/__(.*?)__/g, 'QQQBOLDST$1QQQBOLDEN');
  res = res.replace(/\*(.*?)\*/g, 'QQQITALICST$1QQQITALICEN');
  res = res.replace(/_(.*?)_/g, 'QQQITALICST$1QQQITALICEN');
  res = res.replace(/`(.*?)`/g, 'QQQCODEST$1QQQCODEEN');
  
  // Escape standard LaTeX special characters in the text
  res = escapeLaTeXSpecial(res);
  
  // Restore links
  res = res.replace(/QQQLINKST(.*?)QQQLINKMID(.*?)QQQLINKEN/g, '\\href{$2}{$1}');
  
  // Restore colors
  res = res.replace(/QQQCOLORHEXST(.*?)QQQMID(.*?)QQQCOLOREN/g, '\\textcolor[HTML]{$1}{$2}');
  res = res.replace(/QQQCOLORNAMEST(.*?)QQQMID(.*?)QQQCOLOREN/g, '\\textcolor{$1}{$2}');

  // Restore formatting tags with real LaTeX formatting
  res = res.replace(/QQQBOLDST(.*?)QQQBOLDEN/g, '\\textbf{$1}');
  res = res.replace(/QQQITALICST(.*?)QQQITALICEN/g, '\\textit{$1}');
  res = res.replace(/QQQCODEST(.*?)QQQCODEEN/g, '\\texttt{$1}');
  
  return res;
}
